module: update google/go-cmp to v0.4.0
Currently, test is failed on go devel (at least 641e61db57) because will run checkptr when go test and
which is caused by go-cmp package.
It has been fixed on https://github.com/google/go-cmp/pull/169, Update go-cmp package to latest release.

test result:
  === RUN   TestLiterals/0/"0"
  fatal error: checkptr: unsafe pointer arithmetic

run:
  $ go get -u -d gitub.com/google/go-cmp@latest
  $ go mod tidy

Change-Id: I7881e6c08fa3edb17b10b8b6f5a5e699211a9299